var floatAge, floatDays, intWeeks, floatMonths, intFortnights;
     floatAge = parseFloat(prompt("Enter Age"));
     floatDays = parseFloat(floatAge*365.25);
     floatMonths = parseFloat(floatAge*12);
     intWeeks = parseInt(floatDays/7);
     intFortnights = parseInt(floatDays/14);
     alert("Your Age In Days = " + floatDays);
     alert("Your Age In Months = " + floatMonths);
     alert("Your Age In Weeks = " + intWeeks);
     alert("Your Age In Fortnights = " + intFortnights);